=begin
#TMDB API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 4

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.51
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = SwaggerClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@instance).to be_instance_of(SwaggerClient::DefaultApi)
    end
  end

  # unit tests for account_favorite_movies
  # Favorite Movies
  # Get a user&#x27;s list of favourite movies.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [] :page 
  # @option opts [] :language 
  # @return [InlineResponse20011]
  describe 'account_favorite_movies test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_favorite_tv
  # Favorite TV Shows
  # Get a user&#x27;s list of favourite TV shows.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [] :page 
  # @option opts [] :language 
  # @return [InlineResponse20012]
  describe 'account_favorite_tv test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_lists
  # Lists
  # Get all of the lists you&#x27;ve created.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [] :page 
  # @return [InlineResponse20010]
  describe 'account_lists test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_movie_recommendations
  # Recommended Movies
  # Get a user&#x27;s list of recommended movies.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [] :page 
  # @option opts [] :language 
  # @return [InlineResponse20014]
  describe 'account_movie_recommendations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_movie_watchlist
  # Watchlist Movies
  # Get a user&#x27;s movie watchlist.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [] :page 
  # @option opts [] :language 
  # @return [InlineResponse20014]
  describe 'account_movie_watchlist test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_rated_movies
  # Rated Movies
  # Get a user&#x27;s rated movies.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [] :page 
  # @option opts [] :language 
  # @return [InlineResponse20015]
  describe 'account_rated_movies test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_rated_tv
  # Rated TV Shows
  # Get a user&#x27;s rated TV shows.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [] :page 
  # @option opts [] :language 
  # @return [InlineResponse20016]
  describe 'account_rated_tv test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_tv_recommendations
  # Recommended TV Shows
  # Get a user&#x27;s list of recommended TV shows.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [] :page 
  # @option opts [] :language 
  # @return [InlineResponse20013]
  describe 'account_tv_recommendations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_tv_watchlist
  # Watchlist TV Shows
  # Get a user&#x27;s TV watchlist.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [] :page 
  # @option opts [] :language 
  # @return [InlineResponse20013]
  describe 'account_tv_watchlist test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for auth_create_access_token
  # Create Access Token
  # @param [Hash] opts the optional parameters
  # @option opts [AuthAccessTokenBody] :body 
  # @return [InlineResponse2001]
  describe 'auth_create_access_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for auth_create_request_token
  # Create Request Token
  # @param [Hash] opts the optional parameters
  # @option opts [AuthRequestTokenBody] :body 
  # @return [InlineResponse200]
  describe 'auth_create_request_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for auth_logout
  # Logout
  # Log out of a session.
  # @param [Hash] opts the optional parameters
  # @option opts [AuthAccessTokenBody1] :body 
  # @return [InlineResponse2002]
  describe 'auth_logout test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_add_items
  # Add Items
  # Add items to a list.
  # @param list_id 
  # @param [Hash] opts the optional parameters
  # @option opts [ListIdItemsBody1] :body 
  # @return [InlineResponse2008]
  describe 'list_add_items test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_clear
  # Clear
  # Clear all of the items on a list.
  # @param list_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2006]
  describe 'list_clear test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_create
  # Create
  # Create a new list.
  # @param [Hash] opts the optional parameters
  # @option opts [Model4ListBody] :body 
  # @return [InlineResponse2005]
  describe 'list_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_delete
  # Delete
  # Delete a list.
  # @param list_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2002]
  describe 'list_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_details
  # Details
  # Retrieve a list by id.
  # @param list_id 
  # @param [Hash] opts the optional parameters
  # @option opts [] :language 
  # @option opts [] :page 
  # @return [InlineResponse2003]
  describe 'list_details test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_item_status
  # Item Status
  # Check if an item is on a list.
  # @param list_id 
  # @param media_id 
  # @param media_type 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2009]
  describe 'list_item_status test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_remove_items
  # Remove Items
  # Remove items from a list
  # @param list_id 
  # @param [Hash] opts the optional parameters
  # @option opts [ListIdItemsBody2] :body 
  # @return [InlineResponse2007]
  describe 'list_remove_items test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_update
  # Update
  # Update the details of a list.
  # @param list_id 
  # @param [Hash] opts the optional parameters
  # @option opts [ListListIdBody] :body 
  # @return [InlineResponse2004]
  describe 'list_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_update_items
  # Update Items
  # Update an individual item on a list
  # @param [Hash] opts the optional parameters
  # @option opts [ListIdItemsBody] :body 
  # @return [InlineResponse2007]
  describe 'list_update_items test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
