=begin
#TMDB API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.51
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::SeriesIdRatingBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SeriesIdRatingBody' do
  before do
    # run before each test
    @instance = SwaggerClient::SeriesIdRatingBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SeriesIdRatingBody' do
    it 'should create an instance of SeriesIdRatingBody' do
      expect(@instance).to be_instance_of(SwaggerClient::SeriesIdRatingBody)
    end
  end
  describe 'test attribute "raw_body"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
